### ISSUE TITLE
Seurat incompatibility

### ISSUE THREAD

**Issue by hepcat72** [hepcat72/split-seq-wrappers#6]
**Problem**

Seurat compatibility issue relating to row & column name characters and inadequacy to validate due to small data size.

**Steps to reproduce**

1. Convert the split-seq mtx output to a dense tsv using column names from cell_metadata.csv and row/gene names from genes.csv
2. Run through a standard workflow in seurat such as [this one](https://scrnaseq-course.cog.sanger.ac.uk/website/index.html) (chapter 9).

**Current behavior**

Output must be converted to a dense tsv format and various problems arise that are delineated [here](https://github.com/satijalab/seurat/issues/2887).

**Expected behavior**

Output should be able to be loaded into seurat and used error-free without conversion or massaging.

**Suggested Change**

1. White-list alphanumeric, plus dot and dash.  Replace any non-conforming character with a dash.
2. Download fastq data from the paper and run it through split-seq
3. Run the results through Seurat on galaxy and generate a report as if it was for a real "user".

**Comment**

I have posted about these issues in numerous places:

- https://github.com/satijalab/seurat/issues/2887
- https://www.biostars.org/p/351699/#433704
- https://github.com/galaxyproject/tools-iuc/issues/2983

Useful links:

- https://distill.pub/2016/misread-tsne/
- https://github.com/cole-trapnell-lab/monocle-release/issues/45

My current format conversion script (which needs to be formalized):

```
foreach d ( *filtered )
cd $d
perl -e 'open(CELLS,$ARGV[0]);my $cn=0;$cellbcs={};while(<CELLS>){@cd=split(/,/,$_);$cd[0]=~s/_/-/;$cellbcs->{$cn}=$cd[0];$cn++;}close(CELLS);open(GTF,$ARGV[3]);$gchrs={};while(<GTF>){if(/^(\S+)\t.*?gene_id[\s"]+([^"]+)/){$chr=$1;$acc=$2;$chr=~s/_/-/g;$gchrs->{$acc}=$chr;}}close(GTF);open(GENES,$ARGV[2]);while(<GENES>){chomp;($idx,$acc,$name,$spc)=split(/,|\t/,$_);$idx++;$genes->{$idx}=(exists($gchrs->{$acc}) ? $gchrs->{$acc} : $spc).".${acc}.$name";}$table=[];$l=0;open(MTX,$ARGV[1]);while(<MTX>){next if(/\%/);$l++;chomp;($cellidx,$geneidx,$count)=split(/\s+/,$_);if($l == 1){$len=$cellidx;print(join("\t",map {exists($cellbcs->{$_}) ? $cellbcs->{$_} : $_} (1..$len)),"\n");next;}$mtx->[$geneidx-1]->[$cellidx-1]=$count}my $i=1;foreach my $row (map {defined($_) ? $_ : [map {0} (1..$len)]} @$mtx){unless(exists($genes->{$i})){print STDERR "ERROR: Gene not found: $i\n"}printrow($row,$len,$genes->{$i});$i++}sub printrow {my $ary = $_[0];$size=$_[1];my $gn=$_[2];print("$gn\t",join("\t",map {defined($ary->[$_]) ? exp2int($ary->[$_]) : "0"} (0..($size-1))),"\n")}sub exp2int {$str=$_[0];if($str =~ /^(.*)e\+(\d+)$/){my $n = $1 * 10 ** $2;$n}else{$str}}' cell_metadata.csv DGE.mtx genes.csv ../../../WEI-SPLITSEQ-TT/hg38_mm10/genes.gtf > DGE.fix.tsv
cd ..
end
```

**Comment by hepcat72** [comment]
I figured out how to read in the sparse matrix into R for creating the seurat object directly from the outputs from split-seq:

```
coldata <- read.csv(file="cell_metadata.csv", header=TRUE, sep=",")
colnames <- gsub("[^[:alnum:\\\\-\\\\.] ]", "-", paste(coldata$cell_barcode))

rowdata <- read.csv(file="genes.csv", header=TRUE, sep=",")
rownames <- gsub("[^[:alnum:\\\\-\\\\.] ]", "-", paste(rowdata$genome, rowdata$gene_id, rowdata$gene_name, sep = "."))

library("Matrix")
mtx <- t(as.matrix(readMM("DGE.mtx")))
rownames(mtx) <- rownames
colnames(mtx) <- colnames

pbmc <- CreateSeuratObject(counts = mtx, min.cells = 3, min.features  = 200, project = "SPLITSEQ_TT", assay = "RNA")
```

I'll likely include this in the script I provide to users.

**I still need to figure out how to either add the chromosome to the row names or otherwise subset the matrix for just the mitochondrial gene counts.**  In fact, if I can do that, I could probably just use the ensebl IDs as the row names.

@lparsons - I tried looking into `readr`, but I didn't get very far trying to figure out how to get it to clean up the "bad" characters in the row/col names or join the different columns from either a csv or tsv (or an mtx).  If you think that would be better, do you have a good link that describes how to do that?  I wasted some time looking into read.matrix (which claims to do that) before I found out it was old.

**Comment by lparsons** [comment]
I think I misunderstood you're issue. It looks like you are trying to make a column of character vectors into valid column names. You can use the base R function [`make.names`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/make.names.html) to do that.

[`readr`](https://readr.tidyverse.org/articles/readr.html) would be helpful if you were trying to read data in a set the column names on the resulting dataset.

**Comment by hepcat72** [comment]
OK. So it appears that `make.names` makes the names unique (by prepending 'X') and replaces anything that's not alphanumeric or dot (or optionally underscore) with a dot.  I'm a little concerned though because tutorials I've followed use dashes and pattern matching anchors at the beginning of row names to look for specific genes.  I could change those patterns, but I'm a bit wary that those assumptions may be used elsewhere.  It's probably fine, but I'll feel better when they add the requested naming requirements to the issue I posted.  Someone from the lab responded and answered a lot of my questions, and said that another person from the lab would address the col/row naming requirements.  If we could use `make.names`, identify mitochondrial genes by a different mechanism for subsetting, and get assurances as to any reliance on other potential gene row name pattern matching, I think we'd be solid.

It's also notable that when I use dashes instead of underscores in the cell/column names, the dash gets changed by something to a dot, so maybe `make.names` is called internally somewhere.

**Comment by hepcat72** [comment]
# ToDo

- [x] Add a skeleton R Script for reading in mtx data to deliver to the user
    - Add the option to supply a dense a dense matrix to the R script delivered to the user (unnecessary since I decided to produce one to run through the galaxy seurat tool)
    - [x] Figure out a reliable way of subsetting mitochondrial genes for QC
- [x] Evaluate whether it would be feasible/desireable to provide the user with a dense count matrix either at the lane level, combine level, or both.  The IUC Seurat galaxy tool requires that format.
    - It would be desirable if the user does not intend to use Seurat and just wants to look at the results in Excel in a human-consumable way.
    - It would also allow direct use of the Seurat IUC galaxy tool to provide QC output.
    - It would be easier to not require manual use of R Studio.  Results could be directly transferred to galaxy after single-command processing
    - [x] Add a script to convert the Split-Seq DGE output files to a dense tab-delimited matrix
    - [x] Add a call to that script from the splitseq_run.sh script
    - [x] ? Add a call to that script from the splitseq_combine.sh script
- [x] Confirm using an external data source that the galaxy tool can run successfully on a dense TSV file
    - Initial attempts failed - so apply the col/row name requirements and the necessary parameter settings I've figured out.
    - I will use the outputs of the mouse brain sample analysis being processed for issue #4.

**Comment by lparsons** [comment]
From the docs:
> A syntactically valid name consists of letters, numbers and the dot or underline characters and starts with a letter or the dot not followed by a number. Names such as "`.2way`" are not valid, and neither are the reserved words.

> The definition of a *letter* depends on the current locale, but only ASCII digits are considered to be digits.

> The character "`X`" is prepended if necessary. All invalid characters are translated to "`.`". A missing value is translated to "`NA`". Names which match R keywords have a dot appended to them. Duplicated values are altered by [make.unique](https://stat.ethz.ch/R-manual/R-devel/library/base/html/make.unique.html).

`make.names` has an argument `unique`:
> `unique`  logical; if TRUE, the resulting elements are unique.  This may be desired for, e.g., column names.

`make.unique` has an argument `sep:
> `sep` a character string used to separate a duplicate name from its sequence number.

So, it seems you have a bit of control over how it's done, but not complete. The requirements for row/column in R should at least be handled by `make.names`.

**Comment by hepcat72** [comment]
Yeah.  I read that documentation, but I didn't look at `make.unique`. Even so, it's unclear to me that it's sep argument would be preserved via the call to `make.names`.  Though, I think you're right that the prepending of `X` "when necessary" isn't to make it unique as I had incorrectly inferred.

Regardless, the seurat developers just responded.  They say they use `make.names`, but they allow underscores because they append their own data after them.  That's why the underscores from the splitseq cell_metadata caused a problem.  And other than the `^MT-` in their tutorial (and the appending of metadata using underscores), there are no other assumptions about row/column names in the software.  So I should be able to use `make.names` and set allow_ to false.

**Comment by hepcat72** [comment]
Wait, they don't allow underscores... It's a little confusing.  Maybe they only filter underscores out of row names.  Either way, it sounds like the only reliance on dash is the subsetting in the tutorial.  The software doesn't have any such assumptions.

**Comment by lparsons** [comment]
I don't think the `sep` would pass through, but you ccould use two call, one to `make.unique` with the custom `sep` and then a second to `make.names`.

**Comment by hepcat72** [comment]
Don't need it.  The only place they use dash is in the subset in the tutorial.  So `make.names` is totally sufficient as long as we disallow underscores and use our own mechanism for the identification of mitochondrial genes.

**Comment by hepcat72** [comment]
Yep.  Further confirmation.  It was as I suspected.  They allow underscores in column names because they automatically determine what a cell is - but if it's under 100 cells, they don't do that, which is why the underscores were a problem.

OK.  Now there's a clear and confident path forward.

**Comment by hepcat72** [comment]
Alright.  So I believe this should be what we do.  First, there has to be a custom step to grab the mitochondrial genes from the annotations:
```
grep -E "(hg38_MT|mm10_MT)" genes.gtf | perl -pne 's/.*gene_id ""//;s/"".*//;' > mito_geneids.csv
```
The above uses split-seq's chromosome naming behavior of joining the species name and the chromosome name with an underscore.  We will know the species name ahead of time, but not the mitochondrial chromosome name.

Then, we can successfully subset the data using the mitochondrial accessions.  This also will rely on only using the accessions and plain-jane `make.names`:
```
library(dplyr)
library(Seurat)
library(patchwork)
library(Matrix)

mtx <- t(as.matrix(readMM("DGE.mtx")))

rowdata <- read.csv(file="genes.csv", header=TRUE, sep=",")
rownames(mtx) <- make.names(rowdata$gene_id, unique = TRUE, allow_ = FALSE)

coldata <- read.csv(file="cell_metadata.csv", header=TRUE, sep=",")
colnames(mtx) <- make.names(coldata$cell_barcode, unique = TRUE, allow_ = FALSE)

mitodata <- read.csv(file="mito_geneids.csv", header=FALSE, sep=",")
mitonames <- make.names(mitodata$V1, unique = TRUE, allow_ = FALSE)
mito.genes <- intersect(mitonames,rownames(pbmc@assays[["RNA"]]))

percent.mito <- Matrix::colSums(pbmc@assays[["RNA"]][mito.genes, ])/Matrix::colSums(pbmc@assays[["RNA"]])
pbmc <- AddMetaData(object = pbmc, metadata = percent.mito, col.name = "percent.mito") 
...
```
Everything else is standard.

**Comment by hepcat72** [comment]
This is done, pending the PR.
